#!/usr/bin/env bun
/**
 * Reads all files from dist/client/ and writes a populated shared/client-assets.ts
 * with each asset base64-encoded inline.
 *
 * Run with: bun run scripts/embed-client.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const distClient = path.join(ROOT, "dist", "client");
const outFile = path.join(ROOT, "generated", "client-assets.ts");

const MIME: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".css": "text/css",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".pdf": "application/pdf",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
};

function walkDir(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(abs));
    } else {
      files.push(abs);
    }
  }
  return files;
}

if (!fs.existsSync(distClient)) {
  console.error(`Error: dist/client/ not found at ${distClient}`);
  console.error("Run 'npm run build:client' first.");
  process.exit(1);
}

const files = walkDir(distClient);
console.log(`Embedding ${files.length} files from dist/client/...`);

const entries: string[] = [];
for (const absPath of files) {
  const urlKey = "/" + path.relative(distClient, absPath).split(path.sep).join("/");
  const ext = path.extname(absPath);
  const contentType = MIME[ext] ?? "application/octet-stream";
  const b64 = fs.readFileSync(absPath).toString("base64");
  entries.push(
    `  [${JSON.stringify(urlKey)}, { data: Buffer.from(${JSON.stringify(b64)}, "base64"), contentType: ${JSON.stringify(contentType)} }]`,
  );
}

const output = `// AUTO-GENERATED by scripts/embed-client.ts — DO NOT EDIT
import type { ClientAsset } from "../shared/types.ts";
export const clientAssets: Map<string, ClientAsset> | null = new Map<string, ClientAsset>([
${entries.join(",\n")},
]);
`;

fs.mkdirSync(path.join(ROOT, "generated"), { recursive: true });
fs.writeFileSync(outFile, output);
console.log(`Written: generated/client-assets.ts (${Math.round(output.length / 1024)} KB)`);
